<?php

/**
 * This is the model base class for the table "{{collaborator_group}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CollaboratorGroup".
 *
 * Columns in table "{{collaborator_group}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $name
 * @property string $description
 * @property integer $is_admin_group
 *
 */
abstract class BaseCollaboratorGroup extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{collaborator_group}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CollaboratorGroup|CollaboratorGroups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, name', 'required'),
			array('active, created_time, updated_time, is_admin_group', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('description', 'length', 'max'=>400),
			array('active, description, is_admin_group', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, name, description, is_admin_group', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'is_admin_group' => Yii::t('app', 'Is Admin Group'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('is_admin_group', $this->is_admin_group);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}