<?php

/**
 * This is the model base class for the table "{{order_product}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderProduct".
 *
 * Columns in table "{{order_product}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property integer $order_id
 * @property string $url
 * @property integer $website_type
 * @property string $name
 * @property double $price
 * @property integer $count
 * @property string $vietnamese_name
 * @property string $image
 * @property string $description
 * @property double $web_price
 * @property integer $ordered_count
 * @property string $color
 * @property integer $shop_delivery_order_id
 * @property string $shop_id
 * @property double $real_price
 * @property string $LinkNhaCungCap
 * @property string $TenKho
 */
abstract class BaseOrderProduct extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_product}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderProduct|OrderProducts', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, order_id, url, website_type, price, count', 'required'),
			array('active, created_time, updated_time, order_id, website_type, count, ordered_count, shop_delivery_order_id', 'numerical', 'integerOnly'=>true),
			array('price, web_price, real_price', 'numerical'),
			array('url, name, vietnamese_name, image', 'length', 'max'=>1000),
			array('description', 'length', 'max'=>400),
			array('color, shop_id', 'length', 'max'=>50),
			array('active, name, vietnamese_name, image, description, web_price, ordered_count, color, shop_delivery_order_id, shop_id, real_price', 'default', 'setOnEmpty', 'LinkNhaCungCap' => true, 'value' => null),
			array('id, active, created_time, updated_time, order_id, url, website_type, name, price, count, vietnamese_name, image, description, web_price, ordered_count, color, shop_delivery_order_id, shop_id, real_price', 'safe', 'on','LinkNhaCungCap'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'order_id' => Yii::t('app', 'Order'),
			'url' => Yii::t('app', 'Url'),
			'website_type' => Yii::t('app', 'Website Type'),
			'name' => Yii::t('app', 'Name'),
			'price' => Yii::t('app', 'Price'),
			'count' => Yii::t('app', 'Count'),
			'vietnamese_name' => Yii::t('app', 'Vietnamese Name'),
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'web_price' => Yii::t('app', 'Web Price'),
			'ordered_count' => Yii::t('app', 'Ordered Count'),
			'color' => Yii::t('app', 'Color'),
			'shop_delivery_order_id' => Yii::t('app', 'Shop Delivery Order'),
			'shop_id' => Yii::t('app', 'Shop'),
			'real_price' => Yii::t('app', 'Real Price'),
			//them thuoc tinh moi
			'LinkNhaCungCap' => Yii::t('app', 'LinkNhaCungCap'),
			'TenKho' => Yii::t('app', 'Tenkho'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('website_type', $this->website_type);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('price', $this->price);
		$criteria->compare('count', $this->count);
		$criteria->compare('vietnamese_name', $this->vietnamese_name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('web_price', $this->web_price);
		$criteria->compare('ordered_count', $this->ordered_count);
		$criteria->compare('color', $this->color, true);
		$criteria->compare('shop_delivery_order_id', $this->shop_delivery_order_id);
		$criteria->compare('shop_id', $this->shop_id, true);
		$criteria->compare('real_price', $this->real_price);
		// them thuoc tinh moi
		$criteria->compare('LinkNhaCungCap', $this->LinkNhaCungCap, true);
		$criteria->compare('TenKho', $this->TenKho, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}