<?php

/**
 * This is the model base class for the table "{{order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Order".
 *
 * Columns in table "{{order}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property integer $user_id
 * @property integer $status
 * @property double $total_price
 * @property double $total_weight
 * @property integer $is_paid
 * @property string $description
 * @property double $deposit_amount
 * @property double $total_delivery_price
 * @property double $total_real_price
 * @property integer $total_quantity
 * @property double $total_real_price_ndt
 * @property double $total_price_ndt
 * @property double $total_delivery_price_ndt
 * @property double $weight_price
 * @property double $service_price
 * @property double $final_price
 * @property double $remaining_amount
 * @property double $exchange_rate
 * @property double $shipping_home_price
 * @property double $total_weight_price
 * @property double $service_price_percentage
 * @property double $extra_price
 * @property double $real_exchange_rate
 * @property string $test1
 * 
 */
abstract class BaseOrder extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Order|Orders', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			//them test1
			array('created_time, updated_time, user_id, total_quantity, test1', 'required'),
			array('active, created_time, updated_time, user_id, status, is_paid, total_quantity', 'numerical', 'integerOnly'=>true),
			array('total_price, total_weight, deposit_amount, total_delivery_price, total_real_price, total_real_price_ndt, total_price_ndt, total_delivery_price_ndt, weight_price, service_price, final_price, remaining_amount, exchange_rate, shipping_home_price, total_weight_price, service_price_percentage, extra_price, real_exchange_rate', 'numerical'),
			array('description', 'length', 'max'=>500),
			array('active, status, total_price, total_weight, is_paid, description, deposit_amount, total_delivery_price, total_real_price, total_real_price_ndt, total_price_ndt, total_delivery_price_ndt, weight_price, service_price, final_price, remaining_amount, exchange_rate, shipping_home_price, total_weight_price, service_price_percentage, extra_price, real_exchange_rate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, user_id, status, total_price, total_weight, is_paid, description, deposit_amount, total_delivery_price, total_real_price, total_quantity, total_real_price_ndt, total_price_ndt, total_delivery_price_ndt, weight_price, service_price, final_price, remaining_amount, exchange_rate, shipping_home_price, total_weight_price, service_price_percentage, extra_price, real_exchange_rate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'user_id' => Yii::t('app', 'User'),
			'status' => Yii::t('app', 'Status'),
			'total_price' => Yii::t('app', 'Total Price'),
			'total_weight' => Yii::t('app', 'Total Weight'),
			'is_paid' => Yii::t('app', 'Is Paid'),
			'description' => Yii::t('app', 'Description'),
			'deposit_amount' => Yii::t('app', 'Deposit Amount'),
			'total_delivery_price' => Yii::t('app', 'Total Delivery Price'),
			'total_real_price' => Yii::t('app', 'Total Real Price'),
			'total_quantity' => Yii::t('app', 'Total Quantity'),
			'total_real_price_ndt' => Yii::t('app', 'Total Real Price Ndt'),
			'total_price_ndt' => Yii::t('app', 'Total Price Ndt'),
			'total_delivery_price_ndt' => Yii::t('app', 'Total Delivery Price Ndt'),
			'weight_price' => Yii::t('app', 'Weight Price'),
			'service_price' => Yii::t('app', 'Service Price'),
			'final_price' => Yii::t('app', 'Final Price'),
			'remaining_amount' => Yii::t('app', 'Remaining Amount'),
			'exchange_rate' => Yii::t('app', 'Exchange Rate'),
			'shipping_home_price' => Yii::t('app', 'Shipping Home Price'),
			'total_weight_price' => Yii::t('app', 'Total Weight Price'),
			'service_price_percentage' => Yii::t('app', 'Service Price Percentage'),
			'extra_price' => Yii::t('app', 'Extra Price'),
			'real_exchange_rate' => Yii::t('app', 'Real Exchange Rate'),
			//them nhan
			'test1' => Yii::t('app', 'test111'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('total_price', $this->total_price);
		$criteria->compare('total_weight', $this->total_weight);
		$criteria->compare('is_paid', $this->is_paid);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('deposit_amount', $this->deposit_amount);
		$criteria->compare('total_delivery_price', $this->total_delivery_price);
		$criteria->compare('total_real_price', $this->total_real_price);
		$criteria->compare('total_quantity', $this->total_quantity);
		$criteria->compare('total_real_price_ndt', $this->total_real_price_ndt);
		$criteria->compare('total_price_ndt', $this->total_price_ndt);
		$criteria->compare('total_delivery_price_ndt', $this->total_delivery_price_ndt);
		$criteria->compare('weight_price', $this->weight_price);
		$criteria->compare('service_price', $this->service_price);
		$criteria->compare('final_price', $this->final_price);
		$criteria->compare('remaining_amount', $this->remaining_amount);
		$criteria->compare('exchange_rate', $this->exchange_rate);
		$criteria->compare('shipping_home_price', $this->shipping_home_price);
		$criteria->compare('total_weight_price', $this->total_weight_price);
		$criteria->compare('service_price_percentage', $this->service_price_percentage);
		$criteria->compare('extra_price', $this->extra_price);
		$criteria->compare('real_exchange_rate', $this->real_exchange_rate);
		// them test1
		$criteria->compare('test1', $this->test1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}