<?php

/**
 * This is the model base class for the table "{{notification}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notification".
 *
 * Columns in table "{{notification}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property integer $user_id
 * @property integer $type
 * @property string $params
 * @property integer $is_read
 *
 */
abstract class BaseNotification extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{notification}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notification|Notifications', $n);
	}

	public static function representingColumn() {
		return 'params';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, user_id, type, params', 'required'),
			array('active, created_time, updated_time, user_id, type, is_read', 'numerical', 'integerOnly'=>true),
			array('params', 'length', 'max'=>400),
			array('active, is_read', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, user_id, type, params, is_read', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'user_id' => Yii::t('app', 'User'),
			'type' => Yii::t('app', 'Type'),
			'params' => Yii::t('app', 'Params'),
			'is_read' => Yii::t('app', 'Is Read'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('type', $this->type);
		$criteria->compare('params', $this->params, true);
		$criteria->compare('is_read', $this->is_read);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}