<?php

/**
 * This is the model base class for the table "{{unknown_shop_delivery_order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnknownShopDeliveryOrder".
 *
 * Columns in table "{{unknown_shop_delivery_order}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $delivery_order_code
 * @property double $total_weight
 * @property double $total_volume
 * @property string $description
 * @property string $image
 *
 */
abstract class BaseUnknownShopDeliveryOrder extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{unknown_shop_delivery_order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UnknownShopDeliveryOrder|UnknownShopDeliveryOrders', $n);
	}

	public static function representingColumn() {
		return 'delivery_order_code';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, delivery_order_code', 'required'),
			array('active, created_time, updated_time', 'numerical', 'integerOnly'=>true),
			array('total_weight, total_volume', 'numerical'),
			array('delivery_order_code, image', 'length', 'max'=>200),
			array('description', 'length', 'max'=>500),
			array('active, total_weight, total_volume, description, image', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, delivery_order_code, total_weight, total_volume, description, image', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'delivery_order_code' => Yii::t('app', 'Delivery Order Code'),
			'total_weight' => Yii::t('app', 'Total Weight'),
			'total_volume' => Yii::t('app', 'Total Volume'),
			'description' => Yii::t('app', 'Description'),
			'image' => Yii::t('app', 'Image'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('delivery_order_code', $this->delivery_order_code, true);
		$criteria->compare('total_weight', $this->total_weight);
		$criteria->compare('total_volume', $this->total_volume);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image', $this->image, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}