<?php

/**
 * This is the model base class for the table "{{collaborator}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Collaborator".
 *
 * Columns in table "{{collaborator}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $name
 * @property integer $collaborator_group_id
 * @property integer $type
 * @property string $email
 * @property string $password
 * @property string $phone
 * @property string $skype
 * @property string $facebook_id
 * @property string $facebook_access_token
 * @property string $description
 * @property string $image
 * @property string $image_thumbnail
 * @property integer $is_manager
 * @property string $google_id
 * @property string $google_token
 *
 */
abstract class BaseCollaborator extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{collaborator}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Collaborator|Collaborators', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, name, collaborator_group_id, type, email, password', 'required'),
			array('active, created_time, updated_time, collaborator_group_id, type, is_manager', 'numerical', 'integerOnly'=>true),
			array('name, email, skype, facebook_id, google_id', 'length', 'max'=>50),
			array('password, image, image_thumbnail', 'length', 'max'=>100),
			array('phone', 'length', 'max'=>20),
			array('facebook_access_token, google_token', 'length', 'max'=>1000),
			array('description', 'length', 'max'=>400),
			array('active, phone, skype, facebook_id, facebook_access_token, description, image, image_thumbnail, is_manager, google_id, google_token', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, name, collaborator_group_id, type, email, password, phone, skype, facebook_id, facebook_access_token, description, image, image_thumbnail, is_manager, google_id, google_token', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'name' => Yii::t('app', 'Name'),
			'collaborator_group_id' => Yii::t('app', 'Collaborator Group'),
			'type' => Yii::t('app', 'Type'),
			'email' => Yii::t('app', 'Email'),
			'password' => Yii::t('app', 'Password'),
			'phone' => Yii::t('app', 'Phone'),
			'skype' => Yii::t('app', 'Skype'),
			'facebook_id' => Yii::t('app', 'Facebook'),
			'facebook_access_token' => Yii::t('app', 'Facebook Access Token'),
			'description' => Yii::t('app', 'Description'),
			'image' => Yii::t('app', 'Image'),
			'image_thumbnail' => Yii::t('app', 'Image Thumbnail'),
			'is_manager' => Yii::t('app', 'Is Manager'),
			'google_id' => Yii::t('app', 'Google'),
			'google_token' => Yii::t('app', 'Google Token'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('collaborator_group_id', $this->collaborator_group_id);
		$criteria->compare('type', $this->type);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('skype', $this->skype, true);
		$criteria->compare('facebook_id', $this->facebook_id, true);
		$criteria->compare('facebook_access_token', $this->facebook_access_token, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('image_thumbnail', $this->image_thumbnail, true);
		$criteria->compare('is_manager', $this->is_manager);
		$criteria->compare('google_id', $this->google_id, true);
		$criteria->compare('google_token', $this->google_token, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}