<?php

/**
 * This is the model base class for the table "{{page}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Page".
 *
 * Columns in table "{{page}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $title
 * @property string $page_id
 * @property string $content
 * @property string $image
 * @property string $image_thumbnail
 * @property string $slug
 * @property string $meta_description
 * @property string $meta_keyword
 *
 */
abstract class BasePage extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{page}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Page|Pages', $n);
	}

	public static function representingColumn() {
		return 'page_id';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, page_id, content, slug', 'required'),
			array('active, created_time, updated_time', 'numerical', 'integerOnly'=>true),
			array('title, page_id, image, image_thumbnail, slug', 'length', 'max'=>100),
			array('meta_description, meta_keyword', 'safe'),
			array('active, title, image, image_thumbnail, meta_description, meta_keyword', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, title, page_id, content, image, image_thumbnail, slug, meta_description, meta_keyword', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'title' => Yii::t('app', 'Title'),
			'page_id' => Yii::t('app', 'Page'),
			'content' => Yii::t('app', 'Content'),
			'image' => Yii::t('app', 'Image'),
			'image_thumbnail' => Yii::t('app', 'Image Thumbnail'),
			'slug' => Yii::t('app', 'Slug'),
			'meta_description' => Yii::t('app', 'Meta Description'),
			'meta_keyword' => Yii::t('app', 'Meta Keyword'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('page_id', $this->page_id, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('image_thumbnail', $this->image_thumbnail, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('meta_description', $this->meta_description, true);
		$criteria->compare('meta_keyword', $this->meta_keyword, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}