<?php

/**
 * This is the model base class for the table "{{post}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "{{post}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $title
 * @property string $slug
 * @property string $content
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $short_description
 * @property integer $admin_id
 *
 */
abstract class BasePost extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{post}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, title, slug, content, short_description, admin_id', 'required'),
			array('active, created_time, updated_time, admin_id', 'numerical', 'integerOnly'=>true),
			array('title, slug, meta_keywords, meta_description', 'length', 'max'=>200),
			array('short_description', 'length', 'max'=>400),
			array('active, meta_keywords, meta_description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, title, slug, content, meta_keywords, meta_description, short_description, admin_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'title' => Yii::t('app', 'Title'),
			'slug' => Yii::t('app', 'Slug'),
			'content' => Yii::t('app', 'Content'),
			'meta_keywords' => Yii::t('app', 'Meta Keywords'),
			'meta_description' => Yii::t('app', 'Meta Description'),
			'short_description' => Yii::t('app', 'Short Description'),
			'admin_id' => Yii::t('app', 'Admin'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('meta_keywords', $this->meta_keywords, true);
		$criteria->compare('meta_description', $this->meta_description, true);
		$criteria->compare('short_description', $this->short_description, true);
		$criteria->compare('admin_id', $this->admin_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}