<?php

/**
 * This is the model base class for the table "{{view}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "View".
 *
 * Columns in table "{{view}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property string $url
 * @property string $ip
 * @property string $user_agent
 * @property integer $user_id
 * @property integer $type
 *
 */
abstract class BaseView extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{view}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'View|Views', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, url, ip, user_agent, type', 'required'),
			array('active, created_time, updated_time, user_id, type', 'numerical', 'integerOnly'=>true),
			array('url, user_agent', 'length', 'max'=>200),
			array('ip', 'length', 'max'=>20),
			array('active, user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, url, ip, user_agent, user_id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'url' => Yii::t('app', 'Url'),
			'ip' => Yii::t('app', 'Ip'),
			'user_agent' => Yii::t('app', 'User Agent'),
			'user_id' => Yii::t('app', 'User'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('user_agent', $this->user_agent, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('type', $this->type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}