<?php

/**
 * This is the model base class for the table "{{delivery_order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeliveryOrder".
 *
 * Columns in table "{{delivery_order}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $active
 * @property integer $created_time
 * @property integer $updated_time
 * @property integer $user_id
 * @property string $description
 * @property integer $status
 * @property string $product_name
 * @property string $image
 * @property string $image_url
 *
 */
abstract class BaseDeliveryOrder extends SModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{delivery_order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DeliveryOrder|DeliveryOrders', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('created_time, updated_time, user_id, description', 'required'),
			array('active, created_time, updated_time, user_id, status', 'numerical', 'integerOnly'=>true),
			array('description, image, image_url', 'length', 'max'=>500),
			array('product_name', 'length', 'max'=>200),
			array('active, status, product_name, image, image_url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, active, created_time, updated_time, user_id, description, status, product_name, image, image_url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'active' => Yii::t('app', 'Active'),
			'created_time' => Yii::t('app', 'Created Time'),
			'updated_time' => Yii::t('app', 'Updated Time'),
			'user_id' => Yii::t('app', 'User'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'product_name' => Yii::t('app', 'Product Name'),
			'image' => Yii::t('app', 'Image'),
			'image_url' => Yii::t('app', 'Image Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('active', $this->active);
		$criteria->compare('created_time', $this->created_time);
		$criteria->compare('updated_time', $this->updated_time);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('product_name', $this->product_name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('image_url', $this->image_url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}