<?php return array (
  'content' => '<p><a class="text-guide-listing" href="http://orderhip.com/page_8_huong-dan-tao-don-hang-tren-website-orderhipcom.html" target="_blank" title="Hướng dẫn nạp tiền vào tài khoản khách hàng" style="background-color: rgb(255, 255, 255);">1. Hướng dẫn tạo đơn hàng trên orderhip.com&nbsp;</a><br></p><p><a href="http://orderhip.com/page_12_huong-dan-sua-don-hang-da-tao.html" target="_blank">2. Hướng dẫn sửa đơn hàng đã tạo</a><a class="text-guide-listing" href="http://orderhip.com/page_11_huong-dan-tim-hang-tren-1688-taobao-tmall.html" title="Hướng dẫn  tạo đơn hàng trên hệ thống giaodichtrungquoc.com" target="_blank"></a><a class="text-guide-listing" href="http://orderhip.com/#" target="_blank" title="Hướng dẫn đặt cọc đơn hàng">&nbsp;</a></p><p><a href="http://orderhip.com/page_11_huong-dan-tim-hang-tren-1688-taobao-tmall.html" target="_blank">3. Hướng dẫn tìm hàng trên: 1688.com,  taobao.com,   tmall.com</a><a href="http://orderhip.com/page_12_huong-dan-sua-don-hang-da-tao.html" target="_blank"></a><a class="text-guide-listing" href="http://orderhip.com/#" target="_blank" title="Hướng dẫn đặt cọc đơn hàng"></a><a class="text-guide-listing" href="http://orderhip.com/#" target="_blank" title="Hướng dẫn tải phần mềm chat wangwang để chủ động trao đổi với chủ shop">&nbsp;</a></p><p><a class="text-guide-listing" href="http://orderhip.com/page_13_mot-so-tu-khoa.html" target="_blank" title="Hướng dẫn tải phần mềm chat wangwang để chủ động trao đổi với chủ shop">4. Một số từ khóa tìm kiếm trên các website: taobao.com, 1688.com, tmall.com</a><a class="text-guide-listing" href="http://orderhip.com/cach-thuc-giao-nhan-hang" title="Một số câu hội thoại - giao tiếp cần chuẩn bị khi giao tiếp với chủ shop 1688, taobao">&nbsp;</a></p><p><a class="text-guide-listing" href="http://orderhip.com/home/regulations" title="Một số câu hội thoại - giao tiếp cần chuẩn bị khi giao tiếp với chủ shop 1688, taobao" target="_blank">5. Cách thức giao nhận hàng tại kho của Order Hip</a></p>',
  'video' => '<iframe width="686" height="386" src="https://www.youtube.com/embed/kD0-xvNEt0A" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>',
  'user_page_content1' => '      <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span style="background-color: rgb(255, 255, 255);"><span style="font-size: 18px;">&nbsp; </span><span style="font-size: 18px; font-weight: bold;">* Lưu ý:</span><span style="font-size: 18px;"> &nbsp; &nbsp;</span><span style="font-size: 18px;"> &nbsp;</span> </span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p><ul><li><span style="font-style: italic;">&nbsp;</span></li><li><span style="font-style: italic;">- Mọi thắc mắc về đơn hàng quý khách vui lòng liên hệ CTV để biết thêm chi tiết.<br>- Chuyển khoản đặt cọc hoặc thanh lý đơn hàng <span style="color: rgb(0, 0, 255); background-color: rgb(247, 247, 247); text-decoration-line: underline; font-weight: bold;"><a href="http://orderhip.com/home/contact" target="_blank">tại đây</a>. </span><br>- Nội dung chuyển khoản đặt cọc: <span style="background-color: yellow;"><b>Dat Coc [Mã Đơn]</b>. </span>Nội dung chuyển khoản thanh lý: <b style="background-color: yellow;">Thanh Ly [Mã Đơn].</b><br></span></li><li><span style="font-style: italic;">- Quý khách vui lòng kiểm tra kỹ thông tin chi tiết đơn hàng trước khi đặt cọc hoặc thanh lý đơn.<br></span></li><li><span style="font-style: italic;">- Kiểm tra lộ trình hàng hóa vui lòng liên hệ đặt hàng: <span style="font-weight: bold; text-decoration-line: underline; background-color: rgb(255, 255, 0);">Ms. Mai:&nbsp;01665.398.525.</span></span></li><li><span style="font-style: italic;">- Liên hệ nhận hàng, gửi hàng khi hàng đã về kho Hà Nội vui lòng liên hệ thủ kho: <span style="font-weight: bold; text-decoration-line: underline; background-color: rgb(255, 255, 0);">Mr. Tú: 0936.237.226</span></span></li></ul><p><span style="font-style: italic;">- Kiểm tra đặt cọc, thanh lý đơn liên hệ kế toán: <span style="font-weight: bold; text-decoration-line: underline; background-color: rgb(255, 255, 0);">Ms. Việt: 01663.222.000.</span></span></p><p><br></p>',
  'contact_phones' => 
  array (
    'sale' => '0816.22.66.88',
    'accountant' => '0363.222.000',
    'store' => '0936.237.226',
    'order' => '0365.398.525',
  ),
);